/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeops.dev/scanner/apis/cves/v1alpha1"
)

// FakeImageScanReports implements ImageScanReportInterface
type FakeImageScanReports struct {
	Fake *FakeCvesV1alpha1
}

var imagescanreportsResource = schema.GroupVersionResource{Group: "cves.scanner.appscode.com", Version: "v1alpha1", Resource: "imagescanreports"}

var imagescanreportsKind = schema.GroupVersionKind{Group: "cves.scanner.appscode.com", Version: "v1alpha1", Kind: "ImageScanReport"}

// Get takes name of the imageScanReport, and returns the corresponding imageScanReport object, and an error if there is any.
func (c *FakeImageScanReports) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ImageScanReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(imagescanreportsResource, name), &v1alpha1.ImageScanReport{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageScanReport), err
}

// List takes label and field selectors, and returns the list of ImageScanReports that match those selectors.
func (c *FakeImageScanReports) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ImageScanReportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(imagescanreportsResource, imagescanreportsKind, opts), &v1alpha1.ImageScanReportList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ImageScanReportList{ListMeta: obj.(*v1alpha1.ImageScanReportList).ListMeta}
	for _, item := range obj.(*v1alpha1.ImageScanReportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested imageScanReports.
func (c *FakeImageScanReports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(imagescanreportsResource, opts))
}

// Create takes the representation of a imageScanReport and creates it.  Returns the server's representation of the imageScanReport, and an error, if there is any.
func (c *FakeImageScanReports) Create(ctx context.Context, imageScanReport *v1alpha1.ImageScanReport, opts v1.CreateOptions) (result *v1alpha1.ImageScanReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(imagescanreportsResource, imageScanReport), &v1alpha1.ImageScanReport{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageScanReport), err
}

// Update takes the representation of a imageScanReport and updates it. Returns the server's representation of the imageScanReport, and an error, if there is any.
func (c *FakeImageScanReports) Update(ctx context.Context, imageScanReport *v1alpha1.ImageScanReport, opts v1.UpdateOptions) (result *v1alpha1.ImageScanReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(imagescanreportsResource, imageScanReport), &v1alpha1.ImageScanReport{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageScanReport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeImageScanReports) UpdateStatus(ctx context.Context, imageScanReport *v1alpha1.ImageScanReport, opts v1.UpdateOptions) (*v1alpha1.ImageScanReport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(imagescanreportsResource, "status", imageScanReport), &v1alpha1.ImageScanReport{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageScanReport), err
}

// Delete takes name of the imageScanReport and deletes it. Returns an error if one occurs.
func (c *FakeImageScanReports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(imagescanreportsResource, name, opts), &v1alpha1.ImageScanReport{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeImageScanReports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(imagescanreportsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ImageScanReportList{})
	return err
}

// Patch applies the patch and returns the patched imageScanReport.
func (c *FakeImageScanReports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ImageScanReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(imagescanreportsResource, name, pt, data, subresources...), &v1alpha1.ImageScanReport{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageScanReport), err
}
