/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeops.dev/scanner/apis/scanner/v1alpha1"
	scheme "kubeops.dev/scanner/client/clientset/versioned/scheme"
)

// ImageScanRequestsGetter has a method to return a ImageScanRequestInterface.
// A group's client should implement this interface.
type ImageScanRequestsGetter interface {
	ImageScanRequests() ImageScanRequestInterface
}

// ImageScanRequestInterface has methods to work with ImageScanRequest resources.
type ImageScanRequestInterface interface {
	Create(ctx context.Context, imageScanRequest *v1alpha1.ImageScanRequest, opts v1.CreateOptions) (*v1alpha1.ImageScanRequest, error)
	Update(ctx context.Context, imageScanRequest *v1alpha1.ImageScanRequest, opts v1.UpdateOptions) (*v1alpha1.ImageScanRequest, error)
	UpdateStatus(ctx context.Context, imageScanRequest *v1alpha1.ImageScanRequest, opts v1.UpdateOptions) (*v1alpha1.ImageScanRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ImageScanRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ImageScanRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ImageScanRequest, err error)
	ImageScanRequestExpansion
}

// imageScanRequests implements ImageScanRequestInterface
type imageScanRequests struct {
	client rest.Interface
}

// newImageScanRequests returns a ImageScanRequests
func newImageScanRequests(c *ScannerV1alpha1Client) *imageScanRequests {
	return &imageScanRequests{
		client: c.RESTClient(),
	}
}

// Get takes name of the imageScanRequest, and returns the corresponding imageScanRequest object, and an error if there is any.
func (c *imageScanRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ImageScanRequest, err error) {
	result = &v1alpha1.ImageScanRequest{}
	err = c.client.Get().
		Resource("imagescanrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ImageScanRequests that match those selectors.
func (c *imageScanRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ImageScanRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ImageScanRequestList{}
	err = c.client.Get().
		Resource("imagescanrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested imageScanRequests.
func (c *imageScanRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("imagescanrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a imageScanRequest and creates it.  Returns the server's representation of the imageScanRequest, and an error, if there is any.
func (c *imageScanRequests) Create(ctx context.Context, imageScanRequest *v1alpha1.ImageScanRequest, opts v1.CreateOptions) (result *v1alpha1.ImageScanRequest, err error) {
	result = &v1alpha1.ImageScanRequest{}
	err = c.client.Post().
		Resource("imagescanrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageScanRequest).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a imageScanRequest and updates it. Returns the server's representation of the imageScanRequest, and an error, if there is any.
func (c *imageScanRequests) Update(ctx context.Context, imageScanRequest *v1alpha1.ImageScanRequest, opts v1.UpdateOptions) (result *v1alpha1.ImageScanRequest, err error) {
	result = &v1alpha1.ImageScanRequest{}
	err = c.client.Put().
		Resource("imagescanrequests").
		Name(imageScanRequest.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageScanRequest).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *imageScanRequests) UpdateStatus(ctx context.Context, imageScanRequest *v1alpha1.ImageScanRequest, opts v1.UpdateOptions) (result *v1alpha1.ImageScanRequest, err error) {
	result = &v1alpha1.ImageScanRequest{}
	err = c.client.Put().
		Resource("imagescanrequests").
		Name(imageScanRequest.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageScanRequest).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the imageScanRequest and deletes it. Returns an error if one occurs.
func (c *imageScanRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("imagescanrequests").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *imageScanRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("imagescanrequests").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched imageScanRequest.
func (c *imageScanRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ImageScanRequest, err error) {
	result = &v1alpha1.ImageScanRequest{}
	err = c.client.Patch(pt).
		Resource("imagescanrequests").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
