/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeops.dev/scanner/apis/scanner/v1alpha1"
	scheme "kubeops.dev/scanner/client/clientset/versioned/scheme"
)

// ScanImagesGetter has a method to return a ScanImageInterface.
// A group's client should implement this interface.
type ScanImagesGetter interface {
	ScanImages() ScanImageInterface
}

// ScanImageInterface has methods to work with ScanImage resources.
type ScanImageInterface interface {
	Create(ctx context.Context, scanImage *v1alpha1.ScanImage, opts v1.CreateOptions) (*v1alpha1.ScanImage, error)
	ScanImageExpansion
}

// scanImages implements ScanImageInterface
type scanImages struct {
	client rest.Interface
}

// newScanImages returns a ScanImages
func newScanImages(c *ScannerV1alpha1Client) *scanImages {
	return &scanImages{
		client: c.RESTClient(),
	}
}

// Create takes the representation of a scanImage and creates it.  Returns the server's representation of the scanImage, and an error, if there is any.
func (c *scanImages) Create(ctx context.Context, scanImage *v1alpha1.ScanImage, opts v1.CreateOptions) (result *v1alpha1.ScanImage, err error) {
	result = &v1alpha1.ScanImage{}
	err = c.client.Post().
		Resource("scanimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scanImage).
		Do(ctx).
		Into(result)
	return
}
